language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
notifications:
  email:
    recipients:
      - ehcache-dev@googlegroups.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#ehcache"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
